/**
 * Telegram Bot Foundation — Send daily picks to a Telegram channel/chat.
 *
 * Setup:
 * 1. Create a bot via @BotFather on Telegram → get the bot token
 * 2. Create a channel or get your chat ID
 * 3. Enter the token and chat ID in Roll-Over settings
 *
 * Features:
 * - Send today's top picks as a formatted message
 * - Send accuracy report summary
 * - Schedule daily sends (manual trigger or timed)
 * - Format picks with confidence, market, reasoning
 *
 * API: https://api.telegram.org/bot{token}/sendMessage
 */

import { httpGetDirect } from '../lib/http';

// ─── Configuration ───────────────────────────────────────────────────────────

const STORAGE_KEY_TOKEN = 'rollover_telegram_bot_token';
const STORAGE_KEY_CHAT = 'rollover_telegram_chat_id';

export function getTelegramConfig(): { token: string | null; chatId: string | null } {
  return {
    token: localStorage.getItem(STORAGE_KEY_TOKEN),
    chatId: localStorage.getItem(STORAGE_KEY_CHAT),
  };
}

export function setTelegramConfig(token: string, chatId: string) {
  if (token) localStorage.setItem(STORAGE_KEY_TOKEN, token);
  else localStorage.removeItem(STORAGE_KEY_TOKEN);
  if (chatId) localStorage.setItem(STORAGE_KEY_CHAT, chatId);
  else localStorage.removeItem(STORAGE_KEY_CHAT);
}

export function isTelegramConfigured(): boolean {
  const { token, chatId } = getTelegramConfig();
  return !!(token && chatId);
}

// ─── Message Sending ─────────────────────────────────────────────────────────

/**
 * Send a message to the configured Telegram chat.
 * Uses Telegram Bot API: POST /sendMessage
 */
export async function sendMessage(text: string, parseMode: 'HTML' | 'Markdown' = 'HTML'): Promise<{ ok: boolean; error?: string }> {
  const { token, chatId } = getTelegramConfig();
  if (!token || !chatId) return { ok: false, error: 'Telegram not configured' };

  const url = `https://api.telegram.org/bot${token}/sendMessage`;

  try {
    // Use the Rust HTTP backend to POST (via invoke)
    const { invoke } = await import('@tauri-apps/api/core');
    const response: any = await invoke('http_get', {
      url: `${url}?chat_id=${encodeURIComponent(chatId)}&text=${encodeURIComponent(text)}&parse_mode=${parseMode}`,
      headers: {},
    });

    if (response?.ok) return { ok: true };
    return { ok: false, error: response?.description || 'Unknown Telegram error' };
  } catch (e: any) {
    return { ok: false, error: e?.message || 'Failed to send message' };
  }
}

/**
 * Test the bot connection (sends a test message).
 */
export async function testConnection(): Promise<{ ok: boolean; error?: string }> {
  return sendMessage('Roll-Over Bot connected successfully. Daily picks will appear here.');
}

// ─── Pick Formatting ─────────────────────────────────────────────────────────

export interface TelegramPick {
  homeTeam: string;
  awayTeam: string;
  league: string;
  kickOff: string;
  pick: string;
  market: string;
  confidence: number;
  reasoning: string[];
}

/**
 * Format picks into a Telegram-friendly message (HTML).
 */
export function formatPicksMessage(picks: TelegramPick[], title?: string): string {
  const header = title || `Roll-Over Daily Picks (${new Date().toLocaleDateString()})`;
  let msg = `<b>${header}</b>\n\n`;

  for (const pick of picks) {
    const confEmoji = pick.confidence >= 75 ? '🟢' : pick.confidence >= 60 ? '🟡' : '🔴';
    const time = pick.kickOff ? new Date(pick.kickOff).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '';

    msg += `${confEmoji} <b>${pick.homeTeam} v ${pick.awayTeam}</b>\n`;
    msg += `   ${pick.league} ${time ? '| ' + time : ''}\n`;
    msg += `   Pick: <b>${pick.pick}</b> (${pick.market}) — ${pick.confidence}%\n`;
    if (pick.reasoning.length > 0) {
      msg += `   ${pick.reasoning[0]}\n`;
    }
    msg += '\n';
  }

  msg += `<i>Total: ${picks.length} picks | Generated by Roll-Over v2.1</i>`;
  return msg;
}

/**
 * Format an accuracy summary for Telegram.
 */
export function formatAccuracyMessage(stats: {
  hitRate: number;
  total: number;
  won: number;
  lost: number;
  bestMarket?: { name: string; rate: number };
  bestLeague?: { name: string; rate: number };
}): string {
  let msg = `<b>Roll-Over Accuracy Report</b>\n\n`;
  msg += `Overall: <b>${stats.hitRate}%</b> (${stats.won}W / ${stats.lost}L / ${stats.total} total)\n`;
  if (stats.bestMarket) msg += `Best market: ${stats.bestMarket.name} (${stats.bestMarket.rate}%)\n`;
  if (stats.bestLeague) msg += `Best league: ${stats.bestLeague.name} (${stats.bestLeague.rate}%)\n`;
  msg += `\n<i>Updated: ${new Date().toLocaleString()}</i>`;
  return msg;
}

// ─── Daily Send Functions ────────────────────────────────────────────────────

/**
 * Send today's top picks to Telegram.
 * Call this after Scout runs with results.
 */
export async function sendDailyPicks(picks: TelegramPick[]): Promise<{ ok: boolean; error?: string }> {
  if (!isTelegramConfigured()) return { ok: false, error: 'Telegram not configured' };
  if (picks.length === 0) return { ok: false, error: 'No picks to send' };

  // Filter to top picks (confidence >= 60%, max 10)
  const topPicks = picks
    .filter(p => p.confidence >= 60)
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 10);

  if (topPicks.length === 0) return { ok: false, error: 'No picks above 60% confidence' };

  const message = formatPicksMessage(topPicks);
  return sendMessage(message);
}

/**
 * Send accuracy report to Telegram.
 */
export async function sendAccuracyReport(stats: {
  hitRate: number;
  total: number;
  won: number;
  lost: number;
  bestMarket?: { name: string; rate: number };
  bestLeague?: { name: string; rate: number };
}): Promise<{ ok: boolean; error?: string }> {
  if (!isTelegramConfigured()) return { ok: false, error: 'Telegram not configured' };
  const message = formatAccuracyMessage(stats);
  return sendMessage(message);
}
