/**
 * PredictionGuide — 'How Predictions Work' educational panel.
 * Explains provider strengths, market specialties, and what confidence means.
 * Accessible from a help icon in Match Scout.
 */

import React from 'react';

interface Props {
  open: boolean;
  onClose: () => void;
}

export default function PredictionGuide({ open, onClose }: Props) {
  if (!open) return null;

  return (
    <>
      <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="fixed inset-4 md:inset-x-20 md:inset-y-10 z-50 bg-gray-900 rounded-xl shadow-2xl border border-gray-700 flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-700 bg-gray-800">
          <h2 className="text-lg font-bold text-blue-400">How Predictions Work</h2>
          <button onClick={onClose} className="px-2 py-1 text-gray-400 hover:text-white hover:bg-gray-700 rounded text-lg">
            &#10005;
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">

          {/* Overview */}
          <section>
            <h3 className="text-sm font-bold text-gray-200 mb-2">Overview</h3>
            <p className="text-xs text-gray-400 leading-relaxed">
              Predictions are generated by analyzing historical match data from multiple independent sources.
              Each source has a specialty — the system combines them using weighted consensus to produce
              confidence scores. Higher confidence means more sources agree and more data backs the prediction.
            </p>
          </section>

          {/* Provider Strengths */}
          <section>
            <h3 className="text-sm font-bold text-gray-200 mb-3">Provider Specialties</h3>
            <div className="space-y-2">
              {PROVIDER_INFO.map(p => (
                <div key={p.id} className="flex items-start gap-3 p-2 bg-gray-800 rounded">
                  <span className={`text-[10px] px-1.5 py-0.5 rounded font-bold mt-0.5 ${p.badgeClass}`}>{p.badge}</span>
                  <div>
                    <div className="text-xs font-medium text-gray-300">{p.name}</div>
                    <div className="text-[10px] text-gray-500">{p.specialty}</div>
                    <div className="text-[10px] text-gray-600 mt-0.5">Best for: {p.bestFor}</div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Market Specialties */}
          <section>
            <h3 className="text-sm font-bold text-gray-200 mb-3">Market Specialties</h3>
            <div className="overflow-x-auto">
              <table className="w-full text-[10px]">
                <thead>
                  <tr className="text-gray-500 border-b border-gray-700">
                    <th className="text-left py-1.5 px-2">Market</th>
                    <th className="text-left py-1.5 px-2">Primary Source</th>
                    <th className="text-left py-1.5 px-2">What it uses</th>
                    <th className="text-left py-1.5 px-2">Reliability</th>
                  </tr>
                </thead>
                <tbody>
                  {MARKET_INFO.map((m, i) => (
                    <tr key={i} className="border-b border-gray-800">
                      <td className="py-1.5 px-2 font-medium text-gray-300">{m.market}</td>
                      <td className="py-1.5 px-2 text-gray-400">{m.source}</td>
                      <td className="py-1.5 px-2 text-gray-500">{m.uses}</td>
                      <td className="py-1.5 px-2">
                        <span className={`px-1.5 py-0.5 rounded text-[9px] font-medium ${m.reliabilityClass}`}>{m.reliability}</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          {/* Confidence Explained */}
          <section>
            <h3 className="text-sm font-bold text-gray-200 mb-3">What Confidence Means</h3>
            <div className="space-y-2">
              <div className="flex items-center gap-3 p-2 bg-gray-800 rounded">
                <span className="text-xs font-bold px-2 py-0.5 rounded bg-green-900 text-green-300">75%+</span>
                <div className="text-[10px] text-gray-400">Strong pick. Multiple sources agree, backed by 15+ historical matches. High data quality.</div>
              </div>
              <div className="flex items-center gap-3 p-2 bg-gray-800 rounded">
                <span className="text-xs font-bold px-2 py-0.5 rounded bg-yellow-900 text-yellow-300">55-74%</span>
                <div className="text-[10px] text-gray-400">Moderate pick. Data supports it but fewer data points or some source disagreement.</div>
              </div>
              <div className="flex items-center gap-3 p-2 bg-gray-800 rounded">
                <span className="text-xs font-bold px-2 py-0.5 rounded bg-gray-700 text-gray-400">40-54%</span>
                <div className="text-[10px] text-gray-400">Low confidence. Limited data, weak form signal, or sources conflict. Use with caution.</div>
              </div>
            </div>
          </section>

          {/* Badges Legend */}
          <section>
            <h3 className="text-sm font-bold text-gray-200 mb-3">Badge Legend</h3>
            <p className="text-xs text-gray-500 mb-2">These badges appear next to picks to show which data supports them:</p>
            <div className="flex flex-wrap gap-2">
              {BADGE_LEGEND.map((b, i) => (
                <div key={i} className="flex items-center gap-1.5 px-2 py-1 bg-gray-800 rounded">
                  <span className={`text-[9px] px-1 py-0 rounded font-bold ${b.className}`}>{b.badge}</span>
                  <span className="text-[10px] text-gray-400">{b.meaning}</span>
                </div>
              ))}
            </div>
          </section>

          {/* Data Quality */}
          <section>
            <h3 className="text-sm font-bold text-gray-200 mb-3">Data Quality Indicators</h3>
            <div className="space-y-1.5 text-[10px] text-gray-400">
              <p><span className="text-green-400 font-medium">High</span> — 30+ matches analyzed, multiple providers have data, H2H available</p>
              <p><span className="text-blue-400 font-medium">Medium</span> — 15-30 matches, at least 2 providers, some gaps in data</p>
              <p><span className="text-yellow-400 font-medium">Low</span> — 5-15 matches, limited provider coverage, predictions less reliable</p>
              <p><span className="text-gray-500 font-medium">Insufficient</span> — Teams not in historical database, using only live provider signals</p>
            </div>
          </section>

          {/* Tips */}
          <section>
            <h3 className="text-sm font-bold text-gray-200 mb-2">Tips</h3>
            <ul className="text-[10px] text-gray-400 space-y-1 list-disc list-inside">
              <li>Click "Sync Data" to download historical results — more data = better predictions</li>
              <li>The system improves over time as more matches are stored in the local database</li>
              <li>Predictions for top leagues (EPL, La Liga, Bundesliga) are more reliable than lower divisions</li>
              <li>Click "Analyze" on any match for deep dive: H2H, form, standings, and provider comparison</li>
              <li>The "Compare" tab in Analysis shows what each provider says side-by-side</li>
              <li>Red flags mean the system detected a risk factor — don't ignore them</li>
            </ul>
          </section>
        </div>
      </div>
    </>
  );
}

// ─── Static Data ─────────────────────────────────────────────────────────────

const PROVIDER_INFO = [
  { id: 'historical', name: 'Historical Database', badge: 'DB', badgeClass: 'bg-blue-900 text-blue-300', specialty: '30 years of match results from football-data.co.uk + OpenFootball + StatsBomb', bestFor: 'Form (W/D/L), H2H record, home/away splits, scoring patterns' },
  { id: 'statsbomb', name: 'StatsBomb xG', badge: 'xG', badgeClass: 'bg-purple-900 text-purple-300', specialty: 'Expected Goals data — measures shot quality, not just results', bestFor: 'Over/Under markets, identifying over/underperformers' },
  { id: 'espn', name: 'ESPN', badge: 'ESPN', badgeClass: 'bg-red-900 text-red-300', specialty: 'Current season standings, live fixtures, position data', bestFor: 'Position gap analysis, identifying mismatches (1st vs 18th)' },
  { id: 'thesportsdb', name: 'TheSportsDB', badge: 'SDB', badgeClass: 'bg-green-900 text-green-300', specialty: 'Recent 5 results per team, broad league coverage (24 leagues)', bestFor: 'Current momentum, BTTS trends, team scoring streaks' },
  { id: 'footballdata', name: 'Football-Data.org', badge: 'FD', badgeClass: 'bg-yellow-900 text-yellow-300', specialty: 'Detailed standings with full season stats for 12 European leagues', bestFor: 'Season-long patterns, clean sheet rates, top scorers context' },
  { id: 'sportmonks', name: 'Sportmonks', badge: 'SM', badgeClass: 'bg-cyan-900 text-cyan-300', specialty: 'ML-based predictions, xG, lineups for Danish/Scottish leagues', bestFor: 'Danish Superliga + Scottish Premiership specifics' },
  { id: 'openligadb', name: 'OpenLigaDB', badge: 'OL', badgeClass: 'bg-orange-900 text-orange-300', specialty: 'German football deep dive — goals, scorers, matchday data', bestFor: 'Bundesliga, 2. Bundesliga, DFB-Pokal analysis' },
];

const MARKET_INFO = [
  { market: 'Home Win', source: 'Historical DB + ESPN', uses: 'Home win rate (last 20), position gap, H2H dominance', reliability: 'High', reliabilityClass: 'bg-green-900 text-green-300' },
  { market: 'Away Win', source: 'Historical DB + TheSportsDB', uses: 'Away win rate, current momentum, weak home team detection', reliability: 'Medium', reliabilityClass: 'bg-yellow-900 text-yellow-300' },
  { market: 'Over 1.5', source: 'StatsBomb xG + Historical DB', uses: 'xG efficiency, average goals, O1.5 rate from last 20 matches', reliability: 'High', reliabilityClass: 'bg-green-900 text-green-300' },
  { market: 'Over 2.5', source: 'StatsBomb xG + Historical DB', uses: 'Combined xG, historical O2.5 rate, H2H goals average', reliability: 'Medium', reliabilityClass: 'bg-yellow-900 text-yellow-300' },
  { market: 'BTTS', source: 'TheSportsDB + Historical DB', uses: 'Both teams scoring rate, clean sheet %, recent form streaks', reliability: 'Medium', reliabilityClass: 'bg-yellow-900 text-yellow-300' },
  { market: 'Draw', source: 'Historical DB + ESPN', uses: 'Close win rates, small position gap, H2H draw frequency', reliability: 'Low', reliabilityClass: 'bg-gray-700 text-gray-400' },
];

const BADGE_LEGEND = [
  { badge: 'Form', className: 'bg-blue-900 text-blue-300', meaning: 'Based on recent W/D/L record' },
  { badge: 'H2H', className: 'bg-indigo-900 text-indigo-300', meaning: 'Head-to-head history between these teams' },
  { badge: 'xG', className: 'bg-purple-900 text-purple-300', meaning: 'Expected Goals analysis (shot quality)' },
  { badge: 'Pos', className: 'bg-red-900 text-red-300', meaning: 'League position/standings gap' },
  { badge: 'Trnd', className: 'bg-green-900 text-green-300', meaning: 'Current momentum/streak trend' },
  { badge: 'CS%', className: 'bg-cyan-900 text-cyan-300', meaning: 'Clean sheet percentage' },
];
